### ISSUE TITLE
Issue in the contract function createLedger(), Transaction is getting failed.

### ISSUE THREAD

**Issue by achinkr17** [verified-network/verified-sdk#13]
Preceding function call and response:-
#call SystemObj.createHolder('CounterpartyXYZ', client)
response:
data {
  response: {
    hash: '0xc285a29c7790601c8fe41f3f8a099546aeae8d5cf083f6551f1954edc6e56af6',
    result: [ ]
  },
  status: 0,
  message: ''
}

#Call:
SystemObj.getAccountHolder(client)
#Response:
data {
  response: {
    hash: '',
    result: [ '0x167893c1B56d69477BD8CB96a12EC1f824654d27' ]
  },
  status: 0,
  message: ''
}

#Call:
HolderObj.createLedger('Travel','IndirectExpenses',options)
Response:
![Screenshot from 2021-07-05 16-43-19](https://user-images.githubusercontent.com/39801641/124566027-4a514980-de60-11eb-800f-ea40d38f516d.png)
[`Ropsten's Etherscan contract status`](https://ropsten.etherscan.io/address/0x382aec4ab88BA65b422DAF0C88Db936b10442e64)

**Comment by kallolborah** [comment]
@achinkr17 please follow basic minimum best practices while creating issues. How can anyone debug an issue with a screenshot of an exception ? Pls look into public github repos of other projects and check how issues are reported.

1. which line of code are you facing this issue in ? Is it in the wallet project or the sdk project ? Pls link it.
2. what is the preceding function you have called ? 

@vshall20

**Comment by kallolborah** [comment]
@achinkr17 where exactly in the Dapp/wallet is the code that you are testing createLedger() with ? I will make the changes there, can you also update the Dapp/wallet code ?

@vshall20

**Comment by kallolborah** [comment]
the SDK had a bug. There is a base Holder, Ledger, Account contract but since we create account holders, ledgers, and accounts using the SDK, we need to pass the holderAddress, ledgerAddress, accountAddress that is dynamically created to the constructors - new HolderContract(userWallet, holderAddress), new LedgerContract(userWallet, ledgerAddress), new AccountContract(userWallet, accountAddress).
