### ISSUE TITLE
Error while creating ledger account and get ledger account

### ISSUE THREAD

**Issue by Rahul1297** [verified-network/verified-sdk#4]
HolderContract().createLedger(ledger.ledgerName, ledger.ledgerGroup)

SystemContract().getAccountLedger(accHolder)

![screenshot_20210519_165057](https://user-images.githubusercontent.com/52921317/119338055-26b9b180-bcad-11eb-81dc-1c23acb2f5a7.png)

**Comment by kallolborah** [comment]
fixed in SDK v0.8 - bug in contract constructors in SDK v0.7
