### ISSUE TITLE
Issue in cash contract

### ISSUE THREAD

**Issue by Rahul1297** [verified-network/verified-sdk#9]
```
CashContract().transferFrom(getUserAddress(), getCashContractAddress(debitCurrencyType), amount)

CashContract().transferFrom('0xD75C5b7Cc10974121c3a99d5aDeCEF91C0a54F8F','0x57F4862dEA8F1630c5DC902575150F4917A8D6f0', 1)
```

![image](https://user-images.githubusercontent.com/52921317/120193792-70b90f00-c23a-11eb-9234-db9a8cc978ba.png)

**Comment by kallolborah** [comment]
the missing balanceOf() in the cash contract in SDK was a problem. I added it. 
Also, the CashContract in the SDK represents multiple currencies, so its constructor should take in a currency address in addition to the user wallet. I modified the constructor too. 
Cash is now working.
